battlebot_review/config/routes.rb
Rails.application.routes.draw do
  resources :robots
  root 'welcome#index'

end

battlebot_review/app/models/robot.rb
class Robot < ActiveRecord::Base
  validates :robot_name, presence: true
end

battlebot_review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

battlebot_review/app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.find(params[:id])
  end

  def new
    @robot = Robot.new
  end

  def edit
    @robot = Robot.find(params[:id])
  end

  def create
    @robot = Robot.new(robot_params)

    if @robot.save
      redirect_to @robot
    else
      render 'new'
    end
  end

  def update
    @robot = Robot.find(params[:id])

    if @robot.update(robot_params)
      redirect_to @robot
    else
      render 'edit'
    end
  end

  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy

    redirect_to robots_path
  end

  private
    def robot_params
      params.require(:robot).permit(
        :robot_name, :bot_type, :team, :builder, :wins, :loses)
  end
end

battlebot_review/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

battlebot_review/app/helpers/application_helper.rb
module ApplicationHelper
end

battlebot_review/app/helpers/robots_helper.rb
module RobotsHelper
end

battlebot_review/app/helpers/welcome_helper.rb
module WelcomeHelper
end

battlebot_review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BattlebotReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

battlebot_review/app/views/robots/_form.html.erb
<%= form_for @robot do |f| %>

  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@robot.errors.count, "error") %> prohibited
        this robot from being saved:
      </h2>
      <ul>
        <% @robot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :robot_name %><br>
    <%= f.text_field :robot_name %>
  </p>

  <p>
    <%= f.label :bot_type %><br>
    <%= f.text_field :bot_type %>
  </p>

  <p>
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </p>

  <p>
    <%= f.label :builder %><br>
    <%= f.text_field :builder %>
  </p>

  <p>
    <%= f.label :wins %><br>
    <%= f.text_field :wins %>
  </p>

  <p>
    <%= f.label :loses %><br>
    <%= f.text_field :loses %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

battlebot_review/app/views/robots/edit.html.erb
<h1>Edit BattleBot Information</h1>

<%= render 'form' %>

<%= link_to 'Back', robots_path %>

battlebot_review/app/views/robots/index.html.erb
<h1>BattleBots Review</h1>
<%= link_to 'Enter BattleBot Information', new_robot_path %>
<table>
  <tr>
    <th>Robot</th>
    <th>Type</th>
    <th>Team</th>
    <th>Builder</th>
    <th>Wins</th>
    <th>Loses</th>
    <th colspan="7"></th>
  </tr>

  <% @robots.each do |robot| %>
    <tr>
      <td><%= robot.robot_name %></td>
      <td><%= robot.bot_type %></td>
      <td><%= robot.team %></td>
      <td><%= robot.builder %></td>
      <td><%= robot.wins %></td>
      <td><%= robot.loses %></td>
      <td><%= link_to 'Show', robot_path(robot) %></td>
      <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
      <td><%= link_to 'Destroy', robot_path(robot),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

battlebot_review/app/views/robots/new.html.erb
<h1>Enter BattleBot Information</h1>

<%= render 'form' %>

<%= link_to 'Back', robots_path %>

battlebot_review/app/views/robots/show.html.erb
<p>
  <strong>Robot:</strong>
  <%= @robot.robot_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @robot.bot_type %>
</p>

<p>
  <strong>Team:</strong>
  <%= @robot.team %>
</p>

<p>
  <strong>Builder:</strong>
  <%= @robot.builder %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @robot.wins %>
</p>

<p>
  <strong>Loses:</strong>
  <%= @robot.loses %>
</p>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>

battlebot_review/app/views/welcome/index.html.erb
<h1>Welcome to BattleBots Review</h1>
<p>Review of ABC BattleBots</p>
<p>Information &copy;2015 BattleBots Inc.</p>
<%= link_to 'Enter the World of BattleBots', controller: 'robots' %>